<?php

namespace Sdz\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
	public function getCategoriesList()
	{
		$qb = $this->createQueryBuilder('c')
				   ->select('c')
		           ->groupBy('c.nom')
		           ->distinct(true)
		           ;

		return $qb;
	}
}
