sdzblog_articles_by_page:
    path:    articles-by-page/{page}
    defaults: { _controller: SdzBlogBundle:Blog:articlesByPage, page:1 }
    requirements:
        page: \d*
        _method: GET


sdzblog_accueil:
    path:    /{page}
    defaults: { _controller: SdzBlogBundle:Blog:index, page:1 }
    requirements:
        page: \d*

sdzblog_voir:
    path:    /article/{slug}
    defaults: { _controller: SdzBlogBundle:Blog:voir}
    requirements:
        slug: ^([a-z1-9]+-)*[a-z1-9]+$

sdzblog_ajouter:
    path:    /ajouter
    defaults: { _controller: SdzBlogBundle:Blog:ajouter }

sdzblog_modifier:
    path:    /modifier/{slug}
    defaults: { _controller: SdzBlogBundle:Blog:modifier }
    requirements:
        slug: ^([a-z1-9]+-)*[a-z1-9]+$
sdzblog_supprimer:
    path:    /supprimer/{slug}
    defaults: { _controller: SdzBlogBundle:Blog:supprimer }
    requirements:
        slug: ^([a-z1-9]+-)*[a-z1-9]+$
