fos_user_group_list:
    path: /list
    defaults: { _controller: FOSUserBundle:Group:list }
    requirements:
        _method: GET

fos_user_group_new:
    path: /new
    defaults: { _controller: FOSUserBundle:Group:new }

fos_user_group_show:
    path: /{groupname}
    defaults: { _controller: FOSUserBundle:Group:show }
    requirements:
        _method: GET

fos_user_group_edit:
    path: /{groupname}/edit
    defaults: { _controller: FOSUserBundle:Group:edit }

fos_user_group_delete:
    path: /{groupname}/delete
    defaults: { _controller: FOSUserBundle:Group:delete }
    requirements:
        _method: GET