fos_user_security_login:
    path:     /connexion
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    path:     /login_check
    defaults: { _controller: FOSUserBundle:Security:check }
    requirements:
        _method: POST

fos_user_security_logout:
    path:      /deconnexion
    defaults:  { _controller: FOSUserBundle:Security:logout }